server:
  port: 8080
spring:
  profiles:
    active: test

---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: RestFullApi
  datasource:
    password: Parkour27
    url: jdbc:postgresql://localhost:5432/apiLocals
    username: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgresql
---
spring:
  config:
    activate:
      on-profile: qa
  application:
    name: RestFullApi
  datasource:
    password: Parkour27
    url: jdbc:postgresql://localhost:5432/apiLocals_qa
    username: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgresql
---
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: RestFullApi
  datasource:
    password: Parkour27
    url: jdbc:postgresql://localhost:5432/apiLocals_prod
    username: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgresql
---
spring:
  config:
    activate:
      on-profile: test
  application:
    name: RestFullApi
  datasource:
    password: jotacode
    url: jdbc:postgresql://localhost:5432/apiLocals_test
    username: jota
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgresql